name: yona
home: https://yona.nu/
version: 0.0.6
appVersion: 713
description: The Yona Server backs the Yona mobile app, providing user management, buddy relationship management, web traffic classification and buddy messaging
sources:
  - https://github.com/yonadev/yona-server
maintainers:
  - name: Richard Clark
    email: richard@kerkhofftech.ca
  - name: Bert Roos
    email: bert@famroos.nu
icon: http://www.yona.nu/wp-content/themes/yona/assets/img/yona-logo.png
dependencies:
  - name: stable/mariadb
    version: 0.6.3
 
